### ISSUE TITLE
Can you share your dataset?

### ISSUE THREAD

**Issue by ma3252788** [bdevans/GaborNet#1]
Hello, I saw your code, I think it is great! Then I found out that I am missing the dataset `/work/data/pixel/small` when debugging the code. Can you disclose your dataset? Or can tell me the ge of the data set...

Thank you very much!

**Comment by bdevans** [comment]
Hi, thanks for your interest! We can't yet as we are in the process of publishing our research on this model. Once the paper is out, we will be happy to share the dataset though.

**Comment by ma3252788** [comment]
> Hi, thanks for your interest! We can't yet as we are in the process of publishing our research on this model. Once the paper is out, we will be happy to share the dataset though.

Ok, thank you very much. Do you have a schedule for the publication of your paper now?

**Comment by bdevans** [comment]
I don't have a specific date yet as we are awaiting reviews but hopefully it will be soon.

**Comment by ma3252788** [comment]
> I don't have a specific date yet as we are awaiting reviews but hopefully it will be soon.

God bless you ^_^
